brainup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('brainup_core.urls')),
    path('api/', include('brainup_core.API.urls')),
    path('auth/', include('user_manager.urls')),
    path('admin/', admin.site.urls),
]

brainup_core/API/urls.py
from django.urls import path
from . import views

app_name = "brainup_api"
urlpatterns = [
    path('', views.api_root, name="root"),
    path('collections/', views.CollectionsList.as_view(), name="collections_list"),
    path('collections/<int:pk>/', views.CollectionDetail.as_view(), name="collection_details"),
    path('cards/', views.CardsList.as_view(), name="cards_list"),
    path('cards/<int:pk>', views.CardDetail.as_view(), name="card_details"),
    path('cards/edit', views.CardsListEdit.as_view(), name='cards_list_edit')
]

brainup_core/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:collection_id>/', views.collection, name='collection'),
    path('<int:collection_id>/learning/', views.learning, name='learning'),
    path('<int:collection_id>/<int:card_id>/', views.card, name='card'),
    path('make_card/', views.card_creation, name="card_creation"),
    path('expired_cards/', views.show_expired, name='show_expired'),
    re_path(r'learn_expired/(?P<index>[\w-]+)', views.learn_expired, name='learn_expired'),
    path('make_collection/', views.collection_creation, name="collection_creation")
]

user_manager/urls.py
from django.urls import path

from user_manager import views

app_name = 'user_manager'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

brainup_core/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


class Card(models.Model):
    front_side = models.TextField()
    back_side = models.TextField()
    creation_date = models.DateField(auto_now_add=True)
    entry_date = models.DateField(default=datetime.date.today())
    KNOWLEDGE_GRADE = [
        ('1', 'Hard'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
    ]
    knowledge = models.CharField(
        max_length=1,
        choices=KNOWLEDGE_GRADE,
        default='1'
    )
    collection = models.ForeignKey('CardsCollection', on_delete=models.CASCADE, related_name='cards')

    def __str__(self):
        return f'front: {self.front_side}\nback:{self.back_side}'


class CardsCollection(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='User')
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'title: {self.title}'

brainup_core/forms.py
from django import forms
from brainup_core.models import Card, CardsCollection


class CardCreationForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = [
            'front_side',
            'back_side',
            'collection'
        ]


class CollectionCreationForm(forms.ModelForm):
    class Meta:
        model = CardsCollection
        fields = [
            'title',
            'description'
        ]

brainup_core/API/views.py
from django.db.models import QuerySet
from django.http import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView
from ..models import Card, CardsCollection
from rest_framework import generics, permissions, mixins
from .serializers import CollectionsSerializer, CardsListSerializer, CardsListEditSerializer
from rest_framework.authentication import SessionAuthentication, BasicAuthentication


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'cards': reverse('brainup_api:cards_list', request=request, format=format),
        'collections': reverse('brainup_api:collections_list', request=request, format=format)
    })


class CollectionsList(generics.ListCreateAPIView):
    queryset = CardsCollection.objects.all()
    serializer_class = CollectionsSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    def get_queryset(self):
        return self.queryset.filter(author=self.request.user)


class CollectionDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = CardsCollection.objects.all()
    serializer_class = CollectionsSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return self.queryset.filter(author=self.request.user)


class CardsList(generics.ListAPIView):
    queryset = Card.objects.all()
    serializer_class = CardsListSerializer
    permission_classes = [permissions.IsAuthenticated]


class CardsListEdit(APIView):

    def get_queryset(self):
        return Card.objects.filter()

    def get(self, request):
        available_collections = CardsCollection.objects.filter(author=request.user).values('id')
        return Response(self.get_queryset()
                            .filter(collection__in=available_collections)
                            .values('id', 'front_side', 'back_side', 'creation_date', 'entry_date', 'knowledge'))

    def put(self, request):
        data = request.data
        colls_ids = CardsCollection.objects.filter(author=request.user).values('id')
        cards = self.get_queryset().filter(collection__in=colls_ids)
        prepared_cards = QuerySet()
        try:
            for card in data:
                try:
                    current_card = cards.get(id=card['id'])
                except:
                    raise Exception('Some card with given id not found')
                for field in card:
                    if field != 'id':
                        setattr(current_card, field, card[field])
                current_card.save()
        except:
            raise Exception('Something went wrong with saving given cards')
        return Response('Cards saved!')


class CardDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Card.objects.all()
    serializer_class = CardsListSerializer
    permission_classes = [permissions.IsAuthenticated]

brainup_core/views.py
import datetime

from django.core.cache import cache
from django.db.models import Q, Count, F, Value
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CardCreationForm, CollectionCreationForm
from .models import Card, CardsCollection


def index(request):
    if request.user.is_authenticated:
        collections = CardsCollection.objects.filter(author=request.user)
        context = {
            'collections': collections,
            'user': request.user
        }
        return render(request, 'index.html', context)
    else:
        return redirect('user_manager:sign_in')


def card(request, card_id):
    if request.user.is_authenticated:
        context = {
            'front': Card.front_side,
            'back': Card.back_side
        }
        print("context")
        return render(request, 'card.html', context)
    else:
        return redirect('index')


def collection(request, collection_id):
    if request.user.is_authenticated:
        try:
            collection = CardsCollection.objects.filter(author=request.user).get(id=collection_id)
        except:
            collection = None

        context = {
            'collection': collection
        }
        return render(request, 'cards/collection.html', context)
    else:
        return redirect('index')


def card_creation(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CardCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('index'))
        else:
            form = CardCreationForm()
            form.fields['collection'].queryset = CardsCollection.objects.filter(author=request.user)
        return render(request, 'cards/base_creation_form.html', {'form': form})
    else:
        return redirect('index')


def collection_creation(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CollectionCreationForm(request.POST)
            if form.is_valid():
                collection = form.save(commit=False)
                collection.author = request.user
                collection.save()
                return redirect('index')
        else:
            form = CollectionCreationForm()
        return render(request, 'cards/base_creation_form.html', {'form': form})
    else:
        return redirect('index')


def learning(request, collection_id):
    if request.user.is_authenticated:
        if request.method == 'GET':
            collection = list(CardsCollection.objects \
                              .filter(id=collection_id) \
                              .values('cards__id', 'cards__front_side', 'cards__back_side', 'cards__entry_date',
                                      'cards__knowledge'))
            if not collection:
                raise Http404('Collection not found')
            for card in collection:
                card['cards__entry_date'] = card['cards__entry_date'].isoformat()
            return render(request, 'cards/learning.html', {'collection': collection})
    else:
        return HttpResponse('User is not authenticated!')


def show_expired(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            # TODO проверка оптимизированности запроса и их кол-ва
            full_collections = CardsCollection.objects.filter(author=request.user) \
                .filter(
                Q(cards__entry_date__lte=datetime.date.today() - datetime.timedelta(days=0))) \
                .values('id',
                        'title',
                        'cards__id',
                        'cards__front_side',
                        'cards__back_side',
                        'cards__entry_date',
                        'cards__knowledge')
            amount_expired = {}
            expired_collections = list(full_collections.distinct().values('id', 'title').annotate(Count('cards__id')))
            cache.add(request.user.id, full_collections, 240)
            context = {
                'collections': expired_collections
            }
            return render(request, 'show_expired.html', context)


def learn_expired(request, index):
    if request.user.is_authenticated:
        if request.method == 'GET':
            try:
                id = int(index)
            except:
                raise Exception('Wrong index format was given')
            cards = cache.get(request.user.id)
            if id > -1:
                cards = cards.filter(id=id) \
                    .values('id',
                            'cards__id',
                            'cards__front_side',
                            'cards__back_side',
                            'cards__entry_date',
                            'cards__knowledge')
            for card in cards:
                card['cards__entry_date'] = card['cards__entry_date'].isoformat()
            context = {
                'collection': list(cards)
            }
            return render(request, 'cards/learning.html', context)
    else:
        return HttpResponse('User is not authenticated!')

brainup_core/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'brainup/css/styles.css' %}">
    <script src="{% static 'brainup/js/jquery-3.6.0.min.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="row">
    <div class="col-sm-2 " id="side_bar_block">
        {% block sidebar %}
        <div style="position:fixed;" id="side-bar-menu-div">
            <div class="card-header">BrainUp ({{user}})</div>
            <div class="sidebar-nav" id="side_bar">
                <ul class="list-group list-group-flush" id="side_bar_elements">
                    <a class="list-group-item" href="{% url 'index' %}">Home</a>
                    <a class="list-group-item" href="{% url 'show_expired' %}" >Learn</a>
                    <a class="list-group-item" style="opacity:10%">Statistics</a>
                    <a class="list-group-item" href="{% url 'user_manager:sign_out' %}">Log out</a>
                    <div class="list-group-item"></div>
                </ul>
            </div>
        </div>

        {% endblock %}
    </div>
    <div class="col-sm-10" id="general-content-block">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

brainup_core/templates/filter.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<script>let api_url = '{% url 'brainup_api:cards_list' %}'</script>
<script src="{% static 'brainup/js/filter.js' %}"></script>

<div>
    {% if collections %}
    <div id="selectors-block">
    <select class="list-selector" id="container-selector" onchange="container_changed()">
        <option>All</option>
        <option>Unknown</option>
        <option>Bad knowing</option>
        <option>Seems known</option>
        <option>Good knowing</option>
        <option>Almost remembered</option>
        <option>Remembered</option>
    </select>
    <select class="list-selector" id="collection-selector" onclick="collection_changed()">
        <option>All</option>
    </select>
    </div>
    <div id="cards-block"></div> <!-- content block -->
    {% else %}
    <h2>There is no cards available</h2>
    {% endif %}
</div>
    <link rel="stylesheet" href="{% static 'brainup/css/card.css' %}"/>
    <script>
        let collections_list = []
        {% for collection in collections %}
        collections_list.push([{{collection.id}}, '{{collection.title}}'])
        {% endfor %}

    </script>

{% endblock %}

brainup_core/templates/index.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<script src="{% static 'brainup/js/index.js' %}"></script>
<link rel="stylesheet" href="{% static 'brainup/css/index.css' %}"/>

<div id="index-container">
    <div id="adding-buttons">
        <a href="{% url 'card_creation' %}">+Создать карточку</a>
        <a href="{% url 'collection_creation' %}">+Создать коллекцию</a>
    </div>
    {% if collections %}
    <div id="collections-list-container">
        {% for collection in collections %}
            {% if collection.cards.count > 0 %}
                <div class="cards-holder-field-div">
                    <div class="cards-container-div filled-collection" title="Description: {{ collection.description }}" data-id="{{ collection.id }}" data-title="{{collection.title}}">
                        {% if collection.cards.count > 1 %}
                            <div class="back-card-div"></div>
                        {% endif %}
                        {% if collection.cards.count > 2 %}
                            <div class="back-card-div"></div>
                        {% endif %}
                        {% if collection.cards.count > 4 %}
                            <div class="back-card-div"></div>
                        {% endif %}
                        <div class="remove-button"></div>
                        <a href="{% url 'collection' collection.id %}">
                            <div class="main-card-div">
                                <p>cards: {{collection.cards.count}}</p>
                            </div>
                        </a>
                        <p class="title-text">{{ collection.title }}</p>
                    </div>
                </div>
            {% else %}
                <div class="cards-holder-field-div">
                    <div class="cards-container-div empty-collection" title="Description: {{ collection.description }}" data-id="{{ collection.id }}">
                        <p>Collection is empty</p>
                        <div>
                            <p>Add card</p>
                            <img src="{% static 'brainup/sources/plus.png' %}">
                        </div>
                        <div class="remove-button"></div>
                    </div>
                    <p class="title-text">{{ collection.title }}</p>
                </div>
            {% endif %}
        {% endfor %}
        <div class="modal-card-creation">
            <div class="modal-content-container">
                <img class="close-modal-cross" src="{% static 'brainup/sources/cross.png' %}">
                <p class="modal-title-text">Create card</p>
                <div class="modal-content-field">
                    <p>Front</p>
                    <input type="text" size="20" >
                    <p>Back</p>
                    <textarea></textarea>
                    <button>Создать</button>
                </div>
            </div>
        </div>
    </div>


    {% else %}
    <h1>There are no collections available</h1>
    {% endif %}
</div>
<script>
    let collection_api_url = '{% url 'brainup_api:collections_list' %}'

</script>
{% endblock %}

brainup_core/templates/show_expired.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}



<link rel="stylesheet" href="{% static 'brainup/css/show_expired.css' %}">

<div>
    {% if collections %}
    <div class="expired-cards-info-block" style="display:flex; flex-direction:row">
        <p class="page-text">Всего карт для повторения на сегодня: </p>
        <p class="page-text" id="number-holder-1"></p>
    </div>
    <div id="selector-container">
        <p class="page-text">Select collection:</p>
        <select id="collection-selector">
            <option value="-1" data-count="">All</option>
        </select>
    </div>
    <div id="info-container">
        <div class="expired-cards-info-block" style="display:flex; flex-direction:row">
            <p class="page-text">Карт для повторения в выбранной коллекции: </p>
            <p class="page-text" id="number-holder-2"></p>
        </div>
        <button id="start-learn-button">Учить</button>
    </div>

    {% else %}
    <p id="congrats-message">Поздравляю! Ты повторил все необходимые карточки на сегодня!</p>
    {% endif %}
</div>

<script src="{% static 'brainup/js/show_expired.js' %}"></script>
<script>
        let redirect_url = '{% url 'learn_expired' '1'%}'
        let collections_list = [{{collections|safe}}][0]
        console.log(collections_list)
</script>

{% endblock %}