brainup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('brainup_core.urls')),
    path('api/', include('brainup_core.API.urls')),
    path('auth/', include('user_manager.urls')),
    path('admin/', admin.site.urls),
]

user_manager/urls.py
from django.urls import path

from user_manager import views

app_name = 'user_manager'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

user_manager/forms.py
from django.contrib.auth.models import User
from django import forms


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-sm'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control form-control-sm'}),
        }


class SignInForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-sm'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-sm'}))

user_manager/views.py
from django.contrib.auth import login, logout, authenticate
from django.forms.utils import ErrorList
from django.shortcuts import redirect, render

from user_manager.forms import SignUpForm, SignInForm


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data.get('password'))
            new_user.save()
            login(request, new_user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'user_manager/sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                errors = form._errors.setdefault("username", ErrorList())
                errors.append("Incorrect username or password.")
    else:
        form = SignInForm()
    return render(request, 'user_manager/sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('index')

user_manager/templates/user_manager/sign_in.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BrainUp</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'user_manager/svg/logo.svg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'user_manager/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5" style="width: 350px;">
        <div class="d-flex flex-column">
            <img src="{% static 'user_manager/svg/logo.svg' %}" class="mx-auto" alt="logo" width="100" height="100">
            <div class="d-flex justify-content-center">
                <h5 class="card-title">Sing in to BrainUp</h5>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-body">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-group mt-2">
                        {% if form.username.errors %}
                        {% for error in form.username.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-group mt-3">
                        {% if form.password.errors %}
                        {% for error in form.password.errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <div class="d-flex">
                            <div class="me-auto">{{ form.password.label_tag }}</div>
                            <small><a href="#" class="link-underline-hover">Forgot password?</a></small>
                        </div>
                        {{ form.password }}
                    </div>
                    <div class="d-grid mt-3">
                        <input type="submit" class="btn btn-sm btn-block btn-success " value="Sign in">
                    </div>
                </form>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body text-center">
                <p class="card-text">New to BrainUp? <small><a href="{% url 'user_manager:sign_up' %}" class="link-underline-hover">Create an account.</a></small></p>
            </div>
        </div>
    </div>
</body>

</html>

user_manager/templates/user_manager/sign_up.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BrainUp</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'user_manager/svg/logo.svg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'user_manager/css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5" style="width: 350px;">
        <div class="d-flex flex-column">
            <img src="{% static 'user_manager/svg/logo.svg' %}" class="mx-auto" alt="logo" width="100" height="100">
            <div class="d-flex justify-content-center">
                <h5 class="card-title">Create your account</h5>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-body">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-group mt-2">
                        {{ form.username.errors }}
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-group mt-3">
                        {{ form.email.errors }}
                        {{ form.email.label_tag }}
                        {{ form.email }}
                    </div>
                    <div class="form-group mt-3">
                        {{ form.password.errors }}
                        <div class="d-flex">
                            <div class="me-auto">{{ form.password.label_tag }}</div>
                            <small><a href="#" class="link-underline-hover">Forgot password?</a></small>
                        </div>
                        {{ form.password }}
                    </div>
                    <div class="d-grid mt-3">
                        <input type="submit" class="btn btn-sm btn-block btn-success " value="Create account">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>